### PR TITLE
Changes to Py5Vector set_mag() and normalize()

### PR DESCRIPTION
**Pull request by AsadNizami**
Fix for #243.
`set_mag()` works when the magnitude is negative.  However for cases like `(0, 0, 1)` it returns `(-0, -0, -1)`. Is this okay, or should I change it to `(0, 0, -1)`?

### CODE REVIEW

**Comment by hx2A** [comment]
I think it is OK. @villares , what do you think?

In cases like this, we often compare py5 with Processing to get an idea of what is appropriate or what users would expect. Processing's API is a useful guide.

For this Processing code:

```java
PVector v1 = new PVector(0, 0, 5);
PVector v2 = new PVector(0, 0, 0);

println(v1.copy().setMag(-1));
println(v1.copy().div(-1));
println(v2.copy().normalize());
```

```txt
[ -0.0, -0.0, -1.0 ]
[ -0.0, -0.0, -5.0 ]
[ 0.0, 0.0, 0.0 ]
```

If Processing is OK with negative zero, py5 should be also.

This PR would do the exact same thing as Processing except it would issue a warning `'Using normalize on a vector of zero magnitude has no effect'`. I would maybe change the wording of that to "zero vector" instead of "vector of zero magnitude", but other than that, I think this PR is great.

**Comment by villares** [comment]
Wonderful improvement! Thank you @AsadNizami!

**Comment by AsadNizami** [comment]
Pls review!

**Comment by hx2A** [comment]
Thank you, @AsadNizami !

**Pull request merged**
