### PR TITLE
add message to prompt use of save_frame()

### PR DESCRIPTION
**Pull request by zztkm**
#171 

- [ ]  Move import py5 to outside of the if clause for screenshot() and the other frame hooks
- [ ] For screenshot(), suggest using save_frame() instead

I would appreciate it if you could let me know if I have missed something.

backgroud: #170

### CODE REVIEW

**Comment by hx2A** [comment]
Thanks for the PR, @zztkm !

This is a good start. You found the right file and line of code to change to improve the error message.

There is one more change you need to make. Look at the previous line of code:

```python
   if py5.bridge.check_run_method_callstack():
```

The original error message you received was "UnboundLocalError: local variable 'py5' referenced before assignment". That error message came from the above `if` statement.

Do you see how you would get that UnboundLocalError exception on that line if `screenshot()` is used in class mode, where you use the `screenshot()` function's `sketch` param, but would not give a UnboundLocalError exception if `screenshot()` is used in module mode, where you don't use the `skech` param? Trace through the previous lines of code in that function to see what is different in those two scenarios.

You'll need to move one line of code for this next change.

**Comment by zztkm** [comment]
@hx2A thanks !

Okay, I will respond!

I have one question. Should `py5` imports be done inside each function?
Or should I import at the top of this module?

Currently, import is done in each function.

**Comment by hx2A** [comment]
> I have one question. Should py5 imports be done inside each function? Or should I import at the top of this module?

The py5 imports should be done inside each function, as you've done here. This is perfect. 

One of the requirements of py5_tools is to provide a way for users to add jar files to the classpath or set JVM options. This must be done before the JVM is started. When you execute `import py5`, it starts the JVM, and no futher changes to the classpath or JVM options are possible. If `import py5` was at the top of the module anywhere in py5_tools, a user that executes `import py5_tools` would also import py5 and start the JVM. Putting the `import py5` statement inside each function is a way of delaying the import until a later time when py5 has already been imported and the JVM is already running.

**Comment by zztkm** [comment]
@hx2A 

> One of the requirements of py5_tools is to provide a way for users to add jar files to the classpath or set JVM options. This must be done before the JVM is started. When you execute import py5, it starts the JVM, and no futher changes to the classpath or JVM options are possible. If import py5 was at the top of the module anywhere in py5_tools, a user that executes import py5_tools would also import py5 and start the JVM. Putting the import py5 statement inside each function is a way of delaying the import until a later time when py5 has already been imported and the JVM is already running.

I see, so that was the reason.
I learned a lot! Thanks for the merge!

**Comment by hx2A** [comment]
> I see, so that was the reason. I learned a lot! Thanks for the merge!

You are welcome! I'm happy you learned something doing this!

**Pull request merged**
