### PR TITLE
make exit method the way it was before

### PR DESCRIPTION
**Pull request by hx2A**

### CODE REVIEW

**Comment by villares** [comment]
Question... I have no idea of the behaviour to expect...  I think this is fine, I just want you have a look:

After exception the she sketch window is still open (which I think can be useful for debugging)
Then closing the window, `exiting()` will run.

image

image

**Comment by villares** [comment]
Now I see this was a P2D / Jupyter Notebook issue...

**Comment by hx2A** [comment]
> Question... I have no idea of the behaviour to expect... I think this is fine, I just want you have a look:
> 
> After exception the she sketch window is still open (which I think can be useful for debugging) Then closing the window, `exiting()` will run.

Are you using the dev version of py5 I created for testing?

Yes, this is the correct behavior. When an exception is thrown, it should keep the window open. The user might want to see the window to get a better idea of what the error is and what to do about it.

The `exiting()` method gets called when the window assets are disposed of, which is triggered when the window is closed. If there is no error, this happens when the running Sketch is closed. If there is an error, the Sketch is actually paused (permanently), which is necessary to make it possible for the window to be closed without a Java call to `System.exit(0)`, which would shut down the JVM and require the user to restart Python (or a Jupyter Notebook).

Processing doesn't have an analogous `exiting()` method, right? You can register a method that gets called when the Sketch is disposed, but that method registering stuff is really for Processing libraries, not end users. py5 has an exiting method because it already needs to do certain shutdown stuff when the Sketch exits and it was an easy feature to add. It's also useful for OpenCV and releasing webcams.

The title of this PR, "make exit method the way it was before", is a reference to the change I made on the Java side. A month ago I changed some Java code that introduced a py5 bug that I then fixed.

**Comment by villares** [comment]
Cool. Yes, .90dev, perfect!

**Pull request merged**
